name: First-Work-Flow
on: workflow_dispatch
jobs:
 first-job:
   runs-on: ubuntu-latest
   steps:
     - name: print reading
       run: echo "hello world"
     - name: print bye
       run: echo "bye"
