name: second-work-flow
on: workflow_dispatch
jobs:
 second-job:
   runs-on: ubuntu-latest
   steps:
    - name: testing
      run: |
           echo "first output"
           echo "second output"
    - name: newtest
      run: echo " the end"
 
